### ISSUE TITLE
add license and readme

### ISSUE THREAD

**Issue by drmaples** [devopsfaith/krakend-newrelic#4]
I would like to use this code. Could you please add a license and a readme for this repo.

**Comment by kpacha** [comment]
@drmaples we'll add a LICENSE but keep in mind this repo has not been updated in a while due the poor performance of the agent (https://github.com/devopsfaith/krakend-ce/issues/6).

the config should be under the namespace "github_com/letgoapp/krakend_newrelic" for the global extra config. the expected fields and their format are defined at https://github.com/devopsfaith/krakend-newrelic/blob/master/metrics-collector.go#L34

feel free to use this project, as almost every piece of software we publish, it's under the apache 2.0 license

**Comment by trojanh** [comment]
@kpacha any plans to improve the performance of this agent so that it can be included with KrakenD ?

**Comment by kpacha** [comment]
@trojanh there is some work in progress but not for this component. here is the PR for adding the new relic exporter to the opencensus component: https://github.com/devopsfaith/krakend-opencensus/pull/55

**Comment by trojanh** [comment]
Great, that's alot of progress. 

Also now that you have added the comment above, people will rightly check the mentioned PR.

Thanks and cheers ,🙌
